config/routes.rb
Rails.application.routes.draw do

root "tickets#index"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resources :rooms, only: [:create] do
      resources :messages, only:[:index,:create]
    end
  end

  resources :tickets do
    resources :rooms, only: [:create]
    collection do 
      get 'search'
    end
 
    resources :orders, only:[:index, :create]
    resources :comments, only:[:create]
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'IT系' },
    { id: 3, name: 'スポーツ系' },
    { id: 4, name: '医療系' },
    { id: 5, name: '公務員系' },
    { id: 6, name: '民間企業全般' },
    { id: 7, name: '自然系' },
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
     
  validates :text, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :ticket
  belongs_to :user
  attr_accessor :token
end

app/models/price.rb
class Price < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1,000' },
    { id: 3, name: '1,500' }
  ]
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :room_users, dependent: :destroy
    has_many :users, through: :room_users
    has_many :messages, dependent: :destroy
    belongs_to :ticket
   
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room   ,dependent: :destroy
  belongs_to :user   ,dependent: :destroy
end

app/models/student_division.rb
class StudentDivision < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '高校生' },
    { id: 3, name: '大学生' }
  ]
end

app/models/ticket.rb
class Ticket < ApplicationRecord
   belongs_to :user
   has_many :orders, dependent: :destroy
   has_one_attached :image, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :rooms, dependent: :destroy
   
   extend ActiveHash::Associations::ActiveRecordExtensions
      
   belongs_to_active_hash :category
       
   #空の投稿を保存できないようにする
   with_options presence: true do
    validates :image
    validates :name
    validates :introduction
   end
    
   #ジャンルの選択が「--」の時は保存できないようにする
    validates :category_id , numericality: { other_than: 1 } do
    end
  end

app/models/user.rb
class User < ApplicationRecord

  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users ,dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  belongs_to_active_hash :student_division
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

   def index
    @rooms = Room.where(user_id: current_user.id)
    ticket_id = Ticket.find(ticket_id)
   end
  
    # def create
    #     @ticket = Ticket.find(params[:ticket_id])
    #     @user = User.find(current_user.id)
    #     @currentRoomUser = RoomUser.where(user_id: current_user.id)
    #     @RoomUserEntry = RoomUser.where(user_id: @user.id)
    #     @currentRoomUser.each do |cu|
    #      @RoomUserEntry.each do |u|
    #         if cu.room_id == u.room_id && 
    #            @isRoom = true 
    #            @room_id = cu.room_id 
    #         end
    #       end
    #     end
    #     unless @isRoom
    #         @room = Room.new(name: params[:name], ticket_id: params[:ticket_id])
    #      if @room.save
    #             RoomUser.create(room_id: @room.id, user_id: current_user.id)
    #             RoomUser.create(room_id: @room.id, user_id: Ticket.find(params[:ticket_id]).user_id)
    #             redirect_to  user_room_messages_path(Ticket.find(params[:ticket_id]).user_id, @room.id)
    #      else
    #             render :create
    #      end
    #     end
    # end

  def create
    @ticket = Ticket.find(params[:ticket_id])
    room = Room.find_by(ticket_id: @ticket.id)
    if room.present?
      redirect_to user_room_messages_path(@ticket.user_id, room.id)
    else
      @room = Room.new(name: params[:name], ticket_id: @ticket.id)
      if @room.save
        RoomUser.create(room_id: @room.id, user_id: current_user.id)
        RoomUser.create(room_id: @room.id, user_id: @ticket.user_id)
        redirect_to user_room_messages_path(@ticket.user_id, @room.id)
      else
        render :create
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittoKatsuo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
     <%# <%= favicon_link_tag 'favicon.ico' %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='footer'>
 <div class= 'footer-contents'>

   <div class = 'footer-left'>
    <ul>Fish man's<br><br>company</ul>  
    <%= link_to image_tag "fish.png" , class: "fish" %>
   </div> 
    
   <div class = 'footer-center'> 
     <%= link_to 'トップに戻る' , root_path ,class: "footer-list1" %>
    <%= link_to  '検索する'    ,  search_tickets_path ,class:"footer-list2" %>
   </div>


   <div class= 'footer-right'>
    <% if user_signed_in? %>
       <div class="user_nav_grid-6">
         <%= link_to '会員情報変更', edit_user_path(current_user), class: "info-change" %>
         <%= link_to '退会する', user_path(current_user), class: "withdrawal" , method: :delete%>
       </div>
    <% else %>
       <div class="grid-7">
         <%= link_to 'ログイン', new_user_session_path, class: "footer-login" %>
         <%= link_to '新規登録', new_user_registration_path, class: "footer-sign-up" %>
       </div>
    <% end %>  
  </div>

</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class= 'top-bar-contents'>
    <div class="left-top">
     <div class= 'title'>Kitto 勝男</div>
     <%= link_to image_tag "katsuo.png" , class: "katsuo" %>
    </div>

    <div class="right-top">
      <%= search_form_for @p, url:  search_tickets_path do |f| %>
      <% f.label :category_id_name_eq, '商品を検索する' %>
       <%= f.collection_select(:category_id_eq , Category.all , :id, :name ,{prompt: "カテゴリ名"}, {class: "select-box"}) %>
       <%= f.submit '検索' , class: "submit-btn" %>
      <%end%>
    </div>
 </div>


  <div class='nav'>
    <ul class='lists-left'>
      <% if user_signed_in? %>
       <div class='user_nav grid-6'> 
        <%= link_to 'トップページに戻る' , root_path ,class:"item-list" %>
        <%= link_to '出品する' , new_ticket_path , class: "item-new" , method: :get %>
        <%# <%= link_to 'メッセージを確認' ,  user_room_messages_path(current_user.id) ,  class: 'item-message' , method: :get %> 
       </div>
      <%else%>
       <div class="grid-6">
        <%= link_to 'トップページに戻る' , root_path , class: "item-list" %>
       </div>
      <%end%>
    </ul>

   <ul class='lists-right'>
     <% if user_signed_in? %>
      <div class="user_nav grid-6">
          <%= link_to {current_user.nickname} %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete , class:"logout"%>
       </div> 
     <% else %>
       <div class="grid-6">
          <%= link_to 'ログイン', new_user_session_path, class:"login" %>
          <%= link_to '新規登録', new_user_registration_path, class:"sign-up" %>
        </div>
     <% end %>
   </ul> 
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("katsuo-header.png", class:"second-logo"), "/" %>
</header>