config/routes.rb
Rails.application.routes.draw do

root "tickets#index"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resources :rooms, only: [:create] do
      resources :messages, only:[:index,:create]
    end
  end

  resources :tickets do
    resources :rooms, only: [:create]
    collection do 
      get 'search'
    end
 
    resources :orders, only:[:index, :create]
    resources :comments, only:[:create]
  end
 
end

app/models/ticket.rb
class Ticket < ApplicationRecord
   belongs_to :user
   has_many :orders, dependent: :destroy
   has_one_attached :image, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :rooms, dependent: :destroy
   
   extend ActiveHash::Associations::ActiveRecordExtensions
      
   belongs_to_active_hash :category
       
   #空の投稿を保存できないようにする
   with_options presence: true do
    validates :image
    validates :name
    validates :introduction
   end
    
   #ジャンルの選択が「--」の時は保存できないようにする
    validates :category_id , numericality: { other_than: 1 } do
    end
  end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy, :create, :new, :update]
  before_action :search_ticket, only: [:index, :search]
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  before_action :search_ticket, only: [:index, :search]

  def index
      @tickets = Ticket.includes(:user).order('created_at DESC')
      @tickets = Ticket.all 
      set_ticket_column  
  end


  def search
    @tickets = Ticket.includes(:user).order('created_at DESC')
    @tickets = Ticket.all 
    @results = @p.result # 検索条件にマッチした商品の情報を取得
  end

  def new
    @ticket = Ticket.new
    @categories = Category.all
  end

  
  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to '/'
    else
      render 'tickets/new'
    end
  end

  def show
    @comments = Comment.all
    @comment = Comment.new
    @ticket = Ticket.find(params[:id])
    @user = User.find(@ticket.user_id)
   if user_signed_in?
    @currentRoomUser = RoomUser.where(user_id: current_user.id)
    @RoomUserEntry = RoomUser.where(user_id: @user.id)
    @currentRoomUser.each do |cu|
        @RoomUserEntry.each do |u|
            if cu.room_id == u.room_id 
                # @room.ticket.id = @ticket.room_id 
                @isRoom = true
                @roomId = cu.room_id
            end
        end
     end
   end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to ticket_path(@ticket)
    else
      render 'edit'
    end
  end

  def destroy
    if @ticket.destroy
      redirect_to root_path
    else
      redirect_to ticket_path(@ticket.id)
    end
  end
            
  private

  def ticket_params
    params.require(:ticket).permit(:name,:image, :introduction,:category_id,:price).merge(user_id: current_user.id)
  end
  
  def set_item
     @ticket = Ticket.find(params[:id])
  end
  
  
  def update_params
      params.require(:ticket).permit(:name,:image, :introduction, :category_id)[:image_url, :id]
  end

  
  def search_ticket
    @p = Ticket.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def set_ticket_column
   @ticket_name = Ticket.select("name").distinct  # 重複なくnameカラムのデータを取り出す
   @ticket_category_id = Ticket.select("category_id").distinct 
  end
  
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">


  </header>
  <%= render "shared/second-header" %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">チケットを発行する</h2>
    <%= form_with model: @ticket, local: true do |form| %>
    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
   
  
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        カバー画像を選択
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= form.file_field :image, id:"item-image" %>
    
        <%= image_tag @ticket.image.variant(resize:'500x500'), class: 'img-upload' if @ticket.image.attached?%>

      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
         チケットのタイトル
        <span class="indispensable">必須</span>
      </div>
      <%= form.text_area :name , class:"items-text", id:"item-name", placeholder:"チケットのタイトル（（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          詳しい説明
          <span class="indispensable">必須</span>
        </div>
        <%= form.text_area :introduction, class:"items-text", id:"item-info", placeholder:"チケットをご覧いただきありがとうございます。
 このチケットでは〇〇の相談を提供しています。

■ 経験・実績・スキル
 ・◯◯年以上◯◯の経験があります。

■ 提供できること
 ・◯◯の相談にのることができます。

■ こんな人におすすめ
 ・◯◯に興味を持っている方
 ・◯◯を学びたい方

■ 当日の流れとスケジュール
 1. 挨拶
 2. 相談内容をヒアリング
 3. 個別の質問に回答
 4. 終了

■ 調整可能な曜日・時間帯
 ・平日19時以降
 ・土曜日/日曜日 13時から18時

■ 購入にあたってのお願い
 ・当日のお申し込みはご遠慮願います。
 ・3日から1週間前後の余裕を持った日時でお申し込みください。
 ・購入申込時に第三希望まで日時をお知らせください。。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">チケットのジャンル</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= form.collection_select(:category_id , Category.all , :id, :name ,{prompt: ""}, {class: "select-box"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    
  
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= form.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/tickets/index.html.erb
<%= render "shared/header" %>

<div class='title-contents'>
<%# #動的な画像の挿入## %>
<%= link_to image_tag "top-image.png" , class: "meigen" %>

<h1 class='message'>Kitto勝男は学生と社会人のお話の場を作り、成長へのきっかけを生むサービスです。</h1>
<%# #動的な画像の挿入## %>
<div class="good-points">
  <div class="good-point-left">
  学校では出会えない<br><br>希望の進路に近い方と出会える！<br>
   <ul class="good-point-left1">今の自分が気になっているお仕事や<br>お話を聞いた事がないお仕事をしている方々の<br>チケットを確認してみよう！
   </li>
  </div>

  <div class="good-point-right">たくさんの良心的な<br><br>社会人の方とお話ができる！
   <ul class="good-point-right1">高校生1,000円/1h、大学生1,500円/1hで<br>どのチケットも購入可能です！<br>勇気を出して気になった方とお話をしてみよう！
   </li>
  </div>
</div>

  <div class="item-contents">
    <ul class="item-subtitle">新規投稿商品</ul>
    <%# #動的な画像の挿入## %>
  </div>
   
   <ul class="item-lists"> 

     <% @tickets.each do |ticket| %> 
       <%= link_to ticket_path(ticket.id), mathod: :get do %>
        <section class="card">
        
            <%= image_tag ticket.image , class: "card-img"%>
         <div class="card-content">
          <h1 class="card-title">  <%= ticket.name %>  </h1>
          <p class="card-text"><%= ticket.introduction  %> </p>
         </div>
         <div class="card-link">
         <%= link_to "About", ticket_path(ticket.id) %>
         </div>
        </section>
        <% end %> 
       <% end %> 
     </ul> 
        
  <%= render "shared/footer" %>

app/views/tickets/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">


  </header>
  <%= render "shared/second-header" %>
  <div class="items-sell-main">
    
    <h2 class="items-sell-title">チケットを発行する</h2>
    <%= form_with model: @ticket, url:  tickets_path , local: true do |form| %>
    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
   
  
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        カバー画像を選択
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= form.file_field :image, id:"item-image" %>
    
        <%= image_tag @ticket.image.variant(resize:'500x500'), class: 'img-upload' if @ticket.image.attached?%>

      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        チケットのタイトル
        <span class="indispensable">必須</span>
      </div>
      <%= form.text_area :name , class:"items-text", id:"item-name", placeholder:"チケットのタイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          詳しい説明
          <span class="indispensable">必須</span>
        </div>
        <%= form.text_area :introduction, class:"items-text", id:"item-info", placeholder:"チケットをご覧いただきありがとうございます。
 このチケットでは〇〇の相談を提供しています。

■ 経験・実績・スキル
 ・◯◯年以上◯◯の経験があります。

■ 提供できること
 ・◯◯の相談にのることができます。

■ こんな人におすすめ
 ・◯◯に興味を持っている方
 ・◯◯を学びたい方

■ 当日の流れとスケジュール
 1. 挨拶
 2. 相談内容をヒアリング
 3. 個別の質問に回答
 4. 終了

■ 調整可能な曜日・時間帯
 ・平日19時以降
 ・土曜日/日曜日 13時から18時

■ 購入にあたってのお願い
 ・当日のお申し込みはご遠慮願います。
 ・3日から1週間前後の余裕を持った日時でお申し込みください。
 ・購入申込時に第三希望まで日時をお知らせください。。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">チケットのジャンル</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= form.collection_select(:category_id , Category.all , :id, :name ,{prompt: ""}, {class: "select-box"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    
  
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= form.submit "発行する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/tickets/search.html.erb
<%= render "shared/header" %>
<h1 class ="search-result">
  検索の結果
</h1>
<%# 検索結果の個数で条件分岐 %>


<ul class="item-lists"> 

 <% if @results.length !=0 %>
      <% @results.each do |result| %>
     <%= link_to ticket_path(result.id), method: :get do  %> 
     <section class="card">
        <%= image_tag result.image ,class: "card-img"%>
          <div class="card-content">
        <h1 class="card-title"> <%= result.name %> </h1>
        <p class="card-text">   <%= result.introduction  %></p> 
        </div>
        <div class="card-link">
         <%= link_to "About" ,ticket_path(result.id)%>
        </div>
      </section>
     <% end %>
     <% end %>
     </ul>
   <% else %>
  <h1 class ="result">該当するチケットはありませんでしたm(__)m</h1>
  <% end %>

  <%= render "shared/footer" %>

app/views/tickets/show.html.erb
<%# 商品の概要 %>
<div class="item-show">
<%= render "shared/second-header" %>
  <div class="item-box">
    <h1 class="box18">
      <p><%= @ticket.name %></p>
    </h1>
    <div class='item-img-content'>
      <%= image_tag @ticket.image ,class:"item-box-img" %>
     
    </div>
    <%# ログインしていて、なおかつ、ログインしているユーザと出品しているユーザが同一人物でないとき表示しましょう。 %>
   

    <div class="item-explain-box">
      <p><%= @ticket.introduction %></p>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @ticket.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @ticket.category.name %></td>
        </tr>
      </tbody>
    </table>
  
   <% if user_signed_in? && @ticket.user_id == current_user.id  %>
     <%= link_to 'チャットを開始', ticket_rooms_path(@ticket), method: :post, class:"item-red-btn2"%>or</p>
      <%= link_to '商品の編集',  edit_ticket_path  , method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', ticket_path(@ticket.id) , method: :delete, class:'item-destroy' %>
    <% elsif user_signed_in? && @ticket.user_id != current_user.id  %>
    <%= link_to 'チャットを開始', ticket_rooms_path(@ticket), method: :post, class:"item-red-btn2"%>
    <%= link_to '購入画面に進む', ticket_orders_path(@ticket.id) ,method: :get, class:"item-red-btn"%>
   <% end %>

<%# 
  <div class="comment-box">
     <%= form_with model: @comment ,url: ticket_comments_path(@ticket),local: true do |f| %>
       <%# <%= f.text_field :text ,{class: "comment-text"} %>
        <%# <p class="comment-warn">相手のことを考え丁寧なコメントを心がけましょう。</p>
        <button type="submit" class="comment-btn">
            <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
            <%# <span>  %>
              <%# コメントする
              <% f.submit  %> 
            <%# <span> %>
        <%# </button> %>
     <%# <%end%>
  <%# </div> %>
   
   <%# <div id='messages'>
      <% @comments.reverse_each do |comment| %>
     <%# <div class="message-card">
        <div class="upper-message">
          <div class="message-user">
           <p><%= comment.user.nickname</p>
          <%# </div> %>
         <%# <div class="message-date">
           <%= l comment.created_at %>
         <%# </div>
       </div> %>
       <%# <div class="lower-message">
         <div class="message-content">
          <p><%= comment.text</p>   
         <%# </div> %>
       <%# </div>
     </div>
     <% end %> 
    <%# </div> %> 
</div>
  <%= render "shared/footer" %>